name: Karabiner-Elements CI

on:
  push:
    paths-ignore:
      - vendor/cpm-cmake-package-lock

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: macos-15-intel
            arch: x86_64
            run_additional_checks: false
          - runs_on: macos-15
            arch: arm64
            run_additional_checks: true

    runs-on: ${{ matrix.runs_on }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.app

      - name: brew install
        run: brew install xcodegen
      - name: package
        run: make package
      - name: rename dmg
        run: |
          shopt -s nullglob
          dmgs=(Karabiner-Elements-*.dmg)
          test ${#dmgs[@]} -eq 1
          mv "${dmgs[0]}" "${dmgs[0]%.dmg}-${{ matrix.arch }}.dmg"
      - name: upload dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: Karabiner-Elements-dmg-${{ matrix.arch }}
          path: Karabiner-Elements-*-${{ matrix.arch }}.dmg
          if-no-files-found: error
      - name: appendix
        if: ${{ matrix.run_additional_checks }}
        run: ruby scripts/reduce-logs.rb 'make -C appendix'
      - name: tests
        if: ${{ matrix.run_additional_checks }}
        run: ruby scripts/reduce-logs.rb 'make -C tests'
